apiVersion: v1
kind: Secret
metadata:
  name: affine-cloud-secret
type: Opaque
data:
  SIGN_KEY: "{{ .Values.affineCloud.signKey }}"
  MAIL_ACCOUNT: "{{ .Values.affineCloud.mail.account }}"
  MAIL_PASSWORD: "{{ .Values.affineCloud.mail.password }}"
